### PR TITLE
Refresh fix and more

### LINKED ISSUE #14: Empty CSS ruleset
Visual Studio Code complains about this line:

			.imageParagraph img { }

Apparently, it's considered bad form to have an empty CSS ruleset, although I didn't see where, as a practical matter, it should cause any problems.  Maybe document it if it's needed for a weird reason?  @Hk1020

### PR DESCRIPTION
**Pull request by Hk1020**
I think this is done now. 

Closes #14 and #13

### CODE REVIEW

**Comment by AvidGameFan** [comment]
Awesome!

Hmm... if the whole window is the drop area, should we get rid of the dashed box?  It's nice to give people a visual target, but seems unnecessary at that point.

**Comment by Hk1020** [comment]
> Awesome!
> 
> Hmm... if the whole window is the drop area, should we get rid of the dashed box? It's nice to give people a visual target, but seems unnecessary at that point.

Absolutely. I started to play with it but couldn't come up with something pleasing. People need to understand what to do immediately. Feel free to experiment.

**Comment by AvidGameFan** [comment]
I have a great idea on how to modify the box.  Will have to play with it a bit...

**Comment by Hk1020** [comment]
> I have a great idea on how to modify the box. Will have to play with it a bit...

Can’t wait to see it. Base structure is now pure html.  But maybe you first integrate the pull request.

**Pull request merged**
